name: Config
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  sync:
    name: Check for config changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            server/src/configs/default.json
      - name: Run script
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          yarn config-check
      - name: Commit and push changes
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Sync character count for config ref file
