name: Lint
on: [push, pull_request]

jobs:
  lint:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Masterfile
        run: yarn masterfile

      - name: Lint
        run: yarn eslint

      - name: Prettier
        run: yarn prettier

      - name: Build
        run: yarn build
