name: Locales
on: workflow_call

permissions: write-all

jobs:
  locales:
    if: ${{ github.ref_name == 'main' }}
    name: Locales Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          yarn
      - name: Run generating script
        run: |
          yarn locales:generate
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      - name: Configure git
        run: |
          git config --global user.name "turtlesocks-bot"
          git config --global user.email "turtlesocks-bot@users.noreply.github.com"
      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Commit and push changes
        if: ${{ env.changes_exist == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add --all
          git commit --message "chore: sync locales [skip ci]"
          git push
          git checkout develop
          git merge main
          git push origin develop
