name: GitHub Release

on:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  release:
    name: Build & release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Volta
        uses: volta-cli/action@v4
      - name: Echo versions
        run: |
          node --version
          yarn --version
      - name: Install dependencies
        run: yarn --prefer-offline
        env:
          HUSKY: 0
      - name: Build app
        run: yarn build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release
