name: Main CI
on: [push, pull_request]

jobs:
  config:
    uses: ./.github/workflows/config.yml
  locales:
    uses: ./.github/workflows/locales.yml
  release:
    uses: ./.github/workflows/release.yml
    needs: [config, locales]
    if: always()
  docker:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository) && always()
    uses: ./.github/workflows/docker.yml
    needs: [config, locales]
