name: Main CI
on:
  push:
    branches:
      - main
      - develop
      - developmod3

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  config:
    uses: ./.github/workflows/config.yml
  locales:
    uses: ./.github/workflows/locales.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  release:
    needs: [config, locales, lint]
    if: needs.locales.outputs.made_commit != 'true' && needs.config.outputs.made_commit != 'true'
    uses: ./.github/workflows/release.yml
  docker:
    needs: [config, locales, lint]
    if: needs.locales.outputs.made_commit != 'true' && needs.config.outputs.made_commit != 'true'
    uses: ./.github/workflows/docker.yml
