name: Main CI
on:
  push:
    branches:
      - main
      - develop
      - developmod

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  config:
    uses: ./.github/workflows/config.yml
  locales:
    uses: ./.github/workflows/locales.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  release:
    if: always()
    uses: ./.github/workflows/release.yml
    needs: [config, locales, lint]
  docker:
    if: always()
    uses: ./.github/workflows/docker.yml
    needs: [config, locales, lint]
