name: Release
on: [release]

jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Sentry Build
        run: yarn release
